FROM node:20-alpine
RUN apk add --no-cache libc6-compat gcompat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV WATCHPACK_POLLING=true
CMD ["npm", "run", "dev"]
